### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by riseshia** [riseshia/noraneko#1]
- [ ] conditional callback trigger
- [ ] methods which hooked from external library
  - there are not explicitly called, but called outside from code base 
- [ ] layout recognize in render option in view
- [ ] layout recognize in render option in controller
- [x] module_function keyword
- [x] `nconst` level method call
- [x] render with no param
- [ ] inherited method call

**Comment by riseshia** [comment]
Split independent issue
